--CREATE TABLE TBLBLOG(
--BLOGID INT PRIMARY KEY IDENTITY(1,1),
--BLOGBASLIK NVARCHAR(100),
--BLOGICERIK NVARCHAR(4000),
--BLOGTARIH SMALLDATETIME,
--BLOGGORSEL VARCHAR(100),
--BLOGTUR TINYINT,
--BLOGKATEGORI TINYINT
--)

--CREATE TABLE TBLTUR(
--TURID INT PRIMARY KEY IDENTITY(1,1),
--TURADI VARCHAR(20)
--)

--CREATE TABLE TBLKATEGORI(
--KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
--KATEGORIAD VARCHAR(20)
--)

--CREATE TABLE TBLYORUM(
--YORUMID INT PRIMARY KEY IDENTITY(1,1),
--KULANICIAD VARCHAR(20),
--MAIL VARCHAR(50),
--YORUMICERIK VARCHAR(400)
--)

--CREATE TABLE TBLHAKKIMIZDA(
--ID TINYINT PRIMARY KEY IDENTITY(1,1),
--ACIKLAMA VARCHAR(1000)
--)

--CREATE TABLE TBLILETISIM(
--MESAJID INT PRIMARY KEY IDENTITY(1,1),
--ADSOYAD  VARCHAR(50),
--MAIL  VARCHAR(50),
--TELEFON  VARCHAR(50),
--KONU  VARCHAR(50),
--MESAJ  VARCHAR(1000)
--)